name: "Integration Tests"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  analyze:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript', 'python', 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       gh extensions install .
       gh extensions install github/gh-codeql
       ./integration-tests/iterate-cli-versions.sh "${{ matrix.language }}" 3
